### PR TITLE
Feat/37 simple merging of data with dplyr

### PR DESCRIPTION
**Pull request by arunge**
# Version 22.10.4

### New features

- when using _Pandora_ skin, in _Import Data_: option to merge two data tables before import (#37)
- checks for correct column names in file imports
- update column names of files if naming conflicts
- new tests

### Updates
- disable accept button(s) by default in _Import Data_

# Details:
## Select the data
  1. select data (1) and (2)
  2. add data to "merge" tab (3)
image

## Merge the data
  1. select tables to be merged (currently only 2 tables can be merged) (1)
  2. select merge operation (2)
  3. select columns to be joined, either manually (3) and (4), or automatically (5)
  4. optionally: show the merge command (6)
  5. preview the merge (7)
  6. accept the merge -> imports the merged data into the iso-app (8)
image

If "Merge via command line" is selected (above (6), below (1)) one can directly provide an merge command in dplyr style (below (2)). Afterwards, preview (3) and accept the merge (4)
image

  - textInput for dplyr

### CODE REVIEW

**Comment by arunge** [comment]
@jroachell15 Could you test the new feature as described here: https://github.com/Pandora-IsoMemo/iso-app/pull/42#issue-1286138077

However, we must wait for @mgross until he fixes #49 before we can merge this feature into the beta branch.

**Comment by arunge** [comment]
@jroachell15 this new feature is now ready for review. You can start testing. :slightly_smiling_face:

**Comment by jroachell15** [comment]
@arunge 

I was testing https://github.com/Pandora-IsoMemo/iso-app/pull/42#issue-1286138077, but i did not see a `merge data` button in the UI:
image

This is the branch is `feat/37_mergeDataUI` and version `22.6.3`, is this correct?

**Comment by arunge** [comment]
@jroachell15 No, the branch you looked at was already merged and deleted remote. It helps to clean up the local branches from time to time.
Here, you must look at: `feat/37_storeImportList` (The name might be a bit confusing, I went further than I thought at the beginning. :see_no_evil: )
image

**Comment by jroachell15** [comment]
@arunge 

I tested this new feature: 

Scenario 1:
Dataset 1
"Historical database of equines"
Dataset 2
"pig measurements dataset"

image

This returns no result, so i hit "import data" again to start over, but the entire app crashes. Is there a way to fix this?

**Pull request closed without merging**
