### PR TITLE
23.01.4: Feat/91 use ext import module

### PR DESCRIPTION
**Pull request by arunge**
### Updates
- when using _Pandora_ skin:
  - the _Import Data_ module is now imported from the new package IsoAppTools (#91, PR #92)
  - now changes of functionality
  - all redundant code was removed

### CODE REVIEW

**Comment by arunge** [comment]
Checks fail since currently, the new package IsoAppTools is not available. I will check this with @jan-abel-inwt .

**Comment by arunge** [comment]
I added missing docker and jenkins files to iso-app-tools, now all is fine.

**Comment by arunge** [comment]
@f-lukas Can you test the _Import Data_ module that is now comming from the package "IsoAppTools"?

image

**Review by f-lukas — COMMENTED** [review]
When I open the Import Data button for the first time, everything works. If I then close the pop-up and open it again, the Accept and Send to Merge buttons are missing after loading a data set. If I then switch to the Prepare tab within the pop-up, the buttons reappear at the bottom.

Apart from that, I only noticed a small typing error in the Merge tab. It says Select tabel x/y instead of Select table x/y.

Everything else worked fine.

**Review by f-lukas — APPROVED** [review]
I agree, it works now :+1:

**Pull request merged**
