### PR TITLE
Bug/24 fix center and zoom

### PR DESCRIPTION
**Pull request by arunge**
#24 

- fix "no data points" in export
- update map center correctly
- fix bottom of left control panel of interactive map (1), bug was mentioned in the video:
image
- fix behaviour when showing/hiding arrow or scale
- add show/hide legend (2)
- remove logo
- add checkbox to fit map bounds (3)
- add button to apply bounds (4)
- show/hide bounds (5) (boundaries are only a fit to the map displayed on the screen)

image

- add progress bar to load remote data

image

### CODE REVIEW

**Comment by arunge** [comment]
I made several changes to fix some bugs mentioned in the viedeo, so its worth a review.
@jroachell15 Could you check the fixes mentioned in https://github.com/Pandora-IsoMemo/iso-app/pull/26#issue-1210996427 if they are working as expected?

**Review by jroachell15 — APPROVED** [review]
looks great!

**Comment by arunge** [comment]
Unfortunately, I cannot merge yet. I found that if we have much data (e.g. all databases selected), the interference between zoom and map updates makes everything too slow, which only seems to happen if the legend is active. :thinking: 
The map freezes all the time:

image

 I need to fix this first.

**Comment by arunge** [comment]
I was able to remove the re-rendering of the map when the center changes. I had to remove the option to specify a center (1) because it conflicts with the option to fit the boundaries. 

image

One would require two apply buttons here, I believe fitting the boundaries is sufficient.

The issue with the zoom currently remains, the map is slow when zooming because the radius of the dots is currently recalculated if zoom changes.

I checked the export: display == export if height/width in the export popup is not changed.

**Pull request merged**
